Update note

diff --git a/note b/note
--- a/note
+++ b/note
@@ -53,3 +53,79 @@ post_request() {
     error "Failed to parse JSON response"
   fi
 }
+
+
+#--------------------------------------
+
+#!/bin/bash
+
+# Function to handle errors and print debug information
+error() {
+  local msg="${1}"
+  local code="${2:-1}"
+  echo "Error: ${msg}"
+  exit "${code}"
+}
+
+debug() {
+  local msg="${1}"
+  echo "Debug: ${msg}"
+}
+
+# Function to make a GET request
+get_request() {
+  local url="${1}"
+  declare -A headers="${2:-}"
+
+  debug "Sending GET request to ${url}"
+
+  local header_str=""
+  for key in "${!headers[@]}"; do 
+    header_str+="-H '${key}: ${headers[$key]}' "
+  done
+  
+  debug "Headers: ${header_str}"
+
+  response=$(eval curl -s "${header_str}" "${url}")
+  if [ $? -ne 0 ]; then
+    error "Failed to send GET request"
+  fi
+
+  debug "GET request response: ${response}"
+
+  echo "${response}" | jq
+  if [ $? -ne 0 ]; then
+    error "Failed to parse JSON response"
+  fi
+}
+
+# Function to make a POST request
+post_request() {
+  local url="${1}"
+  declare -A headers="${2:-}"
+  local payload="${3:-}"
+
+  debug "Sending POST request to ${url}"
+
+  local header_str=""
+  for key in "${!headers[@]}"; do 
+    header_str+="-H '${key}: ${headers[$key]}' "
+  done
+  
+  debug "Headers: ${header_str}"
+  debug "Payload: ${payload}"
+
+  response=$(eval curl -s -X POST "${header_str}" -d "${payload}" "${url}")
+  if [ $? -ne 0 ]; then
+    error "Failed to send POST request"
+  fi
+
+  debug "POST request response: ${response}"
+
+  echo "${response}" | jq
+  if [ $? -ne 0 ]; then
+    error "Failed to parse JSON response"
+  fi
+}
+
+
